### ISSUE TITLE
Баг при выборке с использованием WITH

### ISSUE THREAD

**Issue by alexsandrskopin** [phact-cmf/phact#10]
Пример:

$ratings = DomainRating::objects()->with(['domain'])->getSql();
 
SELECT
 `author_domain_rating`.*,
  `domain_domain`.`name` AS domain__name,
   `domain_domain`.`city` AS domain__city, 
   `domain_domain`.`language` AS domain__language,
    `domain_domain`.`id` AS domain__id 
FROM `author_domain_rating` 
LEFT JOIN `domain_domain` `domain_domain_1` ON `author_domain_rating`.`domain_id` = `domain_domain_1`.`id`

Ошибка при построении SELECT. domain_domain  надо  domain_domain_1

**Comment by OrderTarget** [comment]
Fixed with #11 by @s0de
