### ISSUE TITLE
Удаление обЪектов Admin Phact.

### ISSUE THREAD

**Issue by alexsandrskopin** [phact-cmf/phact#13]
В админ Phact если выделить несколько объектов и удалить, то у модели не вызывается метод delete. Это происходит из-за как я понимаю 

Comment::objects()->filter(['status' => Comment::STATUS_DECLINED])->delete();
ORM document

И тут кроется проблема так как Если у модели перекрыт метод delete. У пользователя (Администратор, заказчик) остается как бы обходной путь.

**Comment by OrderTarget** [comment]
Можно перекрыть необходимый метод в Admin.
